from selenium import webdriver
qspider=webdriver.Chrome(executable_path="G:/Downloads/New folder/chromedriver/chromedriver.exe")
qspider.get("https://www.facebook.com/")
qspider.maximize_window()
qspider.implicitly_wait(30)
qspider.find_element_by_xpath("//input[@name='firstname']").send_keys("rini")
qspider.find_element_by_xpath("//input[@name='lastname']").send_keys("paul")
qspider.find_element_by_xpath("//input[@id='u_0_o']").send_keys("rinimukkathu@gmail.com")
qspider.find_element_by_xpath("//input[@id='u_0_r']").send_keys("rinimukkathu@gmail.com")
qspider.find_element_by_xpath("//input[@data-type='password']").send_keys("rini")
qspider.find_element_by_xpath("//select[@id='day']").send_keys("14")
qspider.find_element_by_xpath("//select[@id='month']").send_keys("Feb")
qspider.find_element_by_xpath("//select[@title='Year']").send_keys("1992")
qspider.find_element_by_xpath("//input[@id='u_0_9']").click()
qspider.find_element_by_xpath("//button[@name='websubmit']").click()

